const mongoose=require("mongoose")

const UserSchema=new mongoose.Schema({
    username:{
        type:String,
        min:3,
        max:20,
        required:true,
        uniquie:true
    },
    email:{
        type:String,
        max:40,
        required:true,
        unique:true
    },
    password:{
        type:String,
        required:true,
        min:6,
        max:18
    },
    profilePicture:{
        type:String,
        default:"",
    },
    coverPicture:{
        type:String,
        default:"",
    },
    followers:{
        type:Array,
        default:[]
    },
    followings:{
        type:Array,
        default:[]
    },
    isAdmin:{
        type:Boolean,
        default:false
    },
    desc:{
        typr:String,
        default:""
    },
    city:{
        type:String,
        max:40,
        default:""
    },
    from:{
        type:String,
        max:40,
        default:""
    },
    relationship:{
        type:Number,
        enum:[1,2,3]
    }
    },{timestamps:true}
);

module.exports=mongoose.model("User", UserSchema);